version: "3.4"

networks:
  tf2sa-net:
    driver: bridge

volumes:
  tf2sa-web:

services:
  tf2sa-db:
    image: adamcoetzee/tf2sa-db
    container_name: tf2sa-db
    restart: unless-stopped
    networks:
      - tf2sa-net
    build:
      context: scripts/mariadb
      dockerfile: Dockerfile.tf2sa-db
    environment:
      - MARIADB_DATABASE=${TF2SA_MYSQL_DB}
      - MARIADB_USER=${TF2SA_MYSQL_USR}
      - MARIADB_PASSWORD=${TF2SA_MYSQL_PWD}

  tf2sa-backend:
    image: adamcoetzee/tf2sa-backend
    container_name: tf2sa-backend
    restart: unless-stopped
    depends_on:
      - tf2sa-db
    networks:
      - tf2sa-net
    build:
      context: dotnet
      dockerfile: Dockerfile.tf2sa-backend
    environment:
      - TF2SA_MYSQL_HOST=tf2sa-db
      - TF2SA_MYSQL_DB=${TF2SA_MYSQL_DB}
      - TF2SA_MYSQL_USR=${TF2SA_MYSQL_USR}
      - TF2SA_MYSQL_PWD=${TF2SA_MYSQL_PWD}
      - TF2SA_STEAM_API_KEY=${TF2SA_STEAM_API_KEY}

  tf2sa-frontend:
    image: adamcoetzee/tf2sa-frontend
    container_name: tf2sa-frontend
    depends_on:
      - tf2sa-backend
    networks:
      - tf2sa-net
    build:
      context: frontend
      dockerfile: Dockerfile.tf2sa-frontend
    volumes:
      - tf2sa-web:/out:rw

  t2sa-reverse-proxy:
    container_name: t2sa-reverse-proxy
    restart: unless-stopped
    depends_on:
      - tf2sa-backend
      - tf2sa-frontend
    networks:
      - tf2sa-net
    image: nginx:latest
    volumes:
      - ./scripts/iac/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - tf2sa-web:/usr/share/nginx/html:ro
      - /home/ubuntu/certbot/www/:/var/www/certbot/:ro
      - /home/ubuntu/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /home/ubuntu/certbot/www/:/var/www/certbot/:rw
      - /home/ubuntu/certbot/conf/:/etc/letsencrypt/:rw
