FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

# COPY STUFF
COPY . ./

# BUILD
RUN dotnet restore
RUN dotnet publish TF2SA.Web/TF2SA.Web.csproj -c Release -o out

# BUILD RUNTIME
FROM mcr.microsoft.com/dotnet/aspnet:6.0
COPY --from=build-env /out .
ENTRYPOINT ["dotnet", "TF2SA.Web.dll"]