name: continuous deployment

on:
  push:
    branches:

env:
  DOCKER_REGISTRY: docker.io
  TF2SA_MYSQL_HOST: ${{ secrets.TF2SA_MYSQL_HOST }}
  TF2SA_MYSQL_USR: ${{ secrets.TF2SA_MYSQL_USR }}
  TF2SA_MYSQL_PWD: ${{ secrets.TF2SA_MYSQL_PWD }}
  TF2SA_MYSQL_DB: ${{ secrets.TF2SA_MYSQL_DB }}
  TF2SA_STEAM_API_KEY: ${{ secrets.TF2SA_STEAM_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      #- name: setup .net 6 sdk
      #  uses: actions/setup-dotnet@v2
      #  with:
      #    dotnet-version: "6.0.x"

      #- name: install dependencies
      #  run: dotnet restore dotnet/

      #- name: build
      #  run: dotnet build dotnet/ --no-restore /warnaserror

      #- name: run unit tests
      #  run: dotnet test dotnet/TF2SA.Tests.Unit/TF2SA.Tests.Unit.csproj -p:CollectCoverage=True -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=lcov

      #- name: publish coverage report to coveralls.io
      #  uses: coverallsapp/github-action@master
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    path-to-lcov: dotnet/TF2SA.Tests.Unit/TestResults/coverage.info

      #- name: TODO to Issue
      #  uses: alstr/todo-to-issue-action@v4

      - name: build docker images
        run: |
          docker-compose build

      - name: Publish Docker images
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker images
        run: |
          docker-compose push

#      - name: run deployment script
#        uses: fifsky/ssh-action@master
#        with:
#          command: |
#            cd tf2sa
#            git pull origin main
#            sudo docker-compose pull
#            sudo docker-compose down -v
#            sudo docker-compose up -d
#          host: ${{ secrets.SSH_ORACLE_HOST }}
#          user: ubuntu
#          key: ${{ secrets.SSH_ORACLE_PRIVATE}}
