name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: connect
        uses: fifsky/ssh-action@master
        with:
          command: |
            ./deploy.sh
          host: ${{ secrets.SSH_ORACLE_HOST }}
          user: ubuntu
          key: ${{ secrets.SSH_ORACLE_PRIVATE}}
